{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trayport-nginx
  labels:
    app: nginx
    {{- include "trayport-nginx.labels" . | nindent 4 }}
    {{ toYaml .Values.customLabels | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
