apiVersion: v1
kind: Service
metadata:
  name: trayport-nginx
  labels:
    app: nginx
    {{- include "trayport-nginx.labels" . | nindent 4 }}
    {{ toYaml .Values.customLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
